# Generated by Django 5.1.7 on 2025-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('team', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('championships', models.IntegerField()),
                ('teams', models.TextField()),
            ],
        ),
    ]
