# Generated by Django 5.1.7 on 2025-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='/drivers/'),
        ),
        migrations.AlterField(
            model_name='legend',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='/legends/'),
        ),
    ]
